name: checking1

on: push

jobs: 
  just_checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install packages etc
      uses: actions/setup-node@v4
      with: 
        node-version: 22

    - name: start redis
      uses: supercharge/redis-github-action@1.7.0
      with: 
        redis-server: 7
    - name: install dependencies
      run: npm install
      working-directory: ./backend

    - name: install dependencies frontend
      run: npm install
      working-directory: ./frontend

    - name: check linitng
      run: npm run lint
      working-directory: ./frontend

    - name: checking dependencies
      run: npm audit --audit-level=high
      working-directory: ./frontend

    - name: run frontend 
      run: npm run dev &
      working-directory: ./frontend

    - name: start the server
      run: node backend/index.js &
      env: 
        CLIENT_ID : ${{secrets.CLIENT_ID}}
        CLIENT_SECRET : ${{secrets.CLIENT_SECRET}}
        MONGO_DB : ${{secrets.MONGO_DB}}
        PORT : ${{secrets.PORT}}
        RAZOR_KEY_ID : ${{secrets.RAZOR_KEY_ID}}
        RAZOR_SECRET_KEY : ${{secrets.RAZOR_SECRET_KEY}}
        S3_ACCESS_KEY : ${{secrets.S3_ACCESS_KEY}}
        S3_SECRET_KEY : ${{secrets.S3_SECRET_KEY}}
        SESSION_SECRET : ${{secrets.SESSION_SECRET}}

    - name: check api
      run: curl http://localhost:3000/user/getAllProducts
    
    - name: deploy the backend (copying file their)
      uses: appleboy/scp-action@master
      with: 
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USER}}
        key: ${{secrets.EC2_KEY}}
        source: "./backend/*"
        target: "/home/ubuntu/e-commerce/backend"
        
    - name: deploy the backend (running the code)
      uses: appleboy/ssh-action@master
      with: 
        host: ${{secrets.EC2_HOST}}
        username: ${{secrets.EC2_USER}}
        key: ${{secrets.EC2_KEY}}
        script: |
          cd /home/ubuntu/e-commerce
          pm2 delete index
          npm install
          pm2 start backend/index.js -i max
          pm2 save