name: checking1

on: push

jobs: 
  just_checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install packages etc
      uses: actions/setup-node@v4
      with: 
        node-version: 22
    - name: start mongodb
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: 7.0

    - name: start redis
      uses: supercharge/redis-github-action@1.7.0
      with: 
        redis-server: 7
    - name: install dependencies
      run: npm install
      working-directory: ./backend
    
    - name: check api
      run: curl http://localhost:3000/getAllProducts

    - name: install dependencies frontend
      run: npm install
      working-directory: ./frontend

    - name: check linitng
      run: npm run lint
      working-directory: ./frontend

    - name: checking dependencies
      run: npm audit --audit-level=high
      working-directory: ./frontend

    - name: run frontend 
      run: npm run dev &
      working-directory: ./frontend

    - name: start the server
      run: node backend/index.js &
      env: 
        CLIENT_ID : ${{secrets.CLIENT_ID}}
        CLIENT_SECRET : ${{secrets.CLIENT_SECRET}}
        MONGO_DB : ${{secrets.MONGO_DB}}
        PORT : ${{secrets.PORT}}
        RAZOR_KEY_ID : ${{secrets.RAZOR_KEY_ID}}
        RAZOR_SECRET_KEY : ${{secrets.RAZOR_SECRET_KEY}}
        S3_ACCESS_KEY : ${{secrets.S3_ACCESS_KEY}}
        S3_SECRET_KEY : ${{secrets.S3_SECRET_KEY}}
        SESSION_SECRET : ${{secrets.SESSION_SECRET}}